lang: en-CA
title: ~/fcusson
email: felixcusson@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Exploring data analytics, AWS Serverless solutions, and Python development.
  Showcasing projects, insights, and open-source contributions.
url: "https://fcusson.github.io" # the base hostname & protocol for your site, e.g. http://example.com
domain: "fcusson.github.io"
repository: fcusson/fcusson.github.io

sass:
  style: compressed

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: neon # or any valid skin name

plugins:
  - jekyll-feed
  - jekyll-remote-theme

collections:
  projects:
    output: true
  portfolio:
    output: true

header_pages:
  - projects.md
  - blog.md
  - about.md

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/fcusson/"
    - label: "Github"
      icon: "fab fa-fw fa-github"
      url: https://github.com/fcusson
